export const menus = [
    {
        "id": 850,
        "code": "INDEX",
        "leaf": null,
        "method": "GET",
        "name": "首页",
        "order": 1,
        "url": "/index.htm",
        "icon": null,
        "subMenus": []
    },
    {
        "id": 851,
        "code": "MEMBER",
        "leaf": null,
        "method": "GET",
        "name": "会员管理",
        "order": 2,
        "url": "#",
        "icon": null,
        "subMenus": [
            {
                "id": 961,
                "code": "MEMBER-USER",
                "leaf": null,
                "method": "GET",
                "name": "用户综合管理",
                "order": 1,
                "url": "/member/user/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 962,
                "code": "MEMBER-ADDRESS",
                "leaf": null,
                "method": "GET",
                "name": "会员地址管理",
                "order": 2,
                "url": "/member/address/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 963,
                "code": "MEMBER-CLIENT",
                "leaf": null,
                "method": "GET",
                "name": "客户端外部会员",
                "order": 4,
                "url": "/member/client/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 964,
                "code": "TAMEM-MEM",
                "leaf": null,
                "method": "GET",
                "name": "ta会员管理",
                "order": 3,
                "url": "/tamember/member/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 965,
                "code": "TAm-ProductInfo-main",
                "leaf": null,
                "method": "GET",
                "name": "ta产品信息",
                "order": 9999,
                "url": "/tamember/am_product_info/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 966,
                "code": "TAM-InvestmentPortfolio-main",
                "leaf": null,
                "method": "GET",
                "name": "投资组合",
                "order": 9999,
                "url": "/tamember/investment_portfolio/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 967,
                "code": "TAM-TaMemFundAcc-main",
                "leaf": null,
                "method": "GET",
                "name": "ta用户交易账户",
                "order": 9999,
                "url": "/tamember/fund_acct/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 968,
                "code": "TAM-TaBaseProdInfo-main",
                "leaf": null,
                "method": "GET",
                "name": "基础产品信息",
                "order": 9999,
                "url": "/tamember/base_prod_info/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 969,
                "code": "TAM-TaFundAcctOrder-main",
                "leaf": null,
                "method": "GET",
                "name": "基金账户业务单",
                "order": 9999,
                "url": "/tamember/fund_acct_order/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 970,
                "code": "TAM-TaPortfolioDetail-main",
                "leaf": null,
                "method": "GET",
                "name": "ta用户组合资产明细",
                "order": 9999,
                "url": "/tamember/portfolio_detail/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 971,
                "code": "TAM-TaFundAcctOrderStatusInfo-main",
                "leaf": null,
                "method": "GET",
                "name": "业务单状态时间",
                "order": 9999,
                "url": "/tamember/fund_acct_order_status_info/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 972,
                "code": "TAM-TaInvestmentPortfolioDetail-main",
                "leaf": null,
                "method": "GET",
                "name": "投资组合明细",
                "order": 9999,
                "url": "/tamember/investment_portfolio_detail/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1564,
                "code": "MEMBER-MEMBER-MAIN",
                "leaf": null,
                "method": "GET",
                "name": "会员查询",
                "order": 1,
                "url": "/member/member/main.htm",
                "icon": null,
                "subMenus": []
            }
        ]
    },
    {
        "id": 852,
        "code": "FI-FILE",
        "leaf": null,
        "method": "GET",
        "name": "文件管理",
        "order": 12,
        "url": "#",
        "icon": null,
        "subMenus": [
            {
                "id": 959,
                "code": "FI-FILE-LOG",
                "leaf": null,
                "method": "GET",
                "name": "文件操作日志",
                "order": 2,
                "url": "/file/log/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 960,
                "code": "FI-FILE-FILE",
                "leaf": null,
                "method": "GET",
                "name": "文件管理",
                "order": 1,
                "url": "/file/info/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1533,
                "code": "UEDITOR-DEMO-UI",
                "leaf": null,
                "method": "GET",
                "name": "富文本编辑器demo",
                "order": 13,
                "url": "/ueditor/demo.htm",
                "icon": null,
                "subMenus": []
            }
        ]
    },
    {
        "id": 854,
        "code": "PROD",
        "leaf": null,
        "method": "GET",
        "name": "产品管理",
        "order": 4,
        "url": "#",
        "icon": null,
        "subMenus": [
            {
                "id": 1024,
                "code": "FI-CATEGORY-MAIN",
                "leaf": null,
                "method": "GET",
                "name": "产品分类管理",
                "order": 11,
                "url": "/fi/category/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1025,
                "code": "FI-DYNAMIC-MAIN",
                "leaf": null,
                "method": "GET",
                "name": "产品动态数据",
                "order": 10,
                "url": "/fi/dynamic/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1026,
                "code": "FI-PROD-INTEGRATION",
                "leaf": null,
                "method": "GET",
                "name": "产品信息综合管理",
                "order": 2,
                "url": "/fi/prod/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1027,
                "code": "FI-RISK-RESULT-MAIN",
                "leaf": null,
                "method": "GET",
                "name": "测试结果管理",
                "order": 3,
                "url": "/fi/risk/testresult/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1028,
                "code": "FI-RISK-MAIN",
                "leaf": null,
                "method": "GET",
                "name": "测试题目管理",
                "order": 2,
                "url": "/fi/risk/testquestion/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1029,
                "code": "FI-RISK-TEMPLATE",
                "leaf": null,
                "method": "GET",
                "name": "测试模板管理",
                "order": 3,
                "url": "/fi/risk/template/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1030,
                "code": "BASEPROD-INTEGRATION",
                "leaf": null,
                "method": "GET",
                "name": "基础产品综合管理",
                "order": 1,
                "url": "/fi/baseProd/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1031,
                "code": "FI-LIQUIDITY-",
                "leaf": null,
                "method": "GET",
                "name": "产品流动信息管理",
                "order": 3,
                "url": "/fi/liquidity/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1032,
                "code": "FI-COLLECT",
                "leaf": null,
                "method": "GET",
                "name": "募集计划管理",
                "order": 13,
                "url": "/fi/collect/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1033,
                "code": "FI-ASSET-STRATEGY",
                "leaf": null,
                "method": "GET",
                "name": "资产配置策略管理",
                "order": 7,
                "url": "/app/productsManagement/assetAllocationStrategy",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1034,
                "code": "FI-INVEST",
                "leaf": null,
                "method": "GET",
                "name": "投资组合",
                "order": 7,
                "url": "/fi/invest/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1035,
                "code": "FI-FROZEN",
                "leaf": null,
                "method": "GET",
                "name": "产品冻结",
                "order": 16,
                "url": "/fi/frozen/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1036,
                "code": "FI-ASSET-DETAIL",
                "leaf": null,
                "method": "GET",
                "name": "资产配置策略明细",
                "order": 7,
                "url": "/fi/asset_detail/main_overwrite.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1037,
                "code": "FI-ASSET-INFO",
                "leaf": null,
                "method": "GET",
                "name": "底层资产信息管理",
                "order": 12,
                "url": "/fi/asset_info/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1038,
                "code": "FI-INVEST-DETAIL",
                "leaf": null,
                "method": "GET",
                "name": "投资组合明细",
                "order": 9,
                "url": "/fi/invest_del/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1039,
                "code": "FI-IPQ-RESULT",
                "leaf": null,
                "method": "GET",
                "name": "IPQ结果",
                "order": 10,
                "url": "/fi/result/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1040,
                "code": "FI-INVENT",
                "leaf": null,
                "method": "GET",
                "name": "产品库存",
                "order": 19,
                "url": "/fi/invent/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1041,
                "code": "FI-INVENT-CHANGE",
                "leaf": null,
                "method": "GET",
                "name": "产品库存变更日志",
                "order": 21,
                "url": "/fi/invent_change/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1042,
                "code": "FI-ASS-RECOMMENDATION",
                "leaf": null,
                "method": "GET",
                "name": "推荐资产配置策略管理",
                "order": 7,
                "url": "/fi/ass/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1043,
                "code": "FI-PROD-CUT",
                "leaf": null,
                "method": "GET",
                "name": "产品交易切割",
                "order": 23,
                "url": "/fi/cut/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1044,
                "code": "FI-IPQ-QUESTION",
                "leaf": null,
                "method": "GET",
                "name": "IPQ问题",
                "order": 9,
                "url": "/fi/question/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1045,
                "code": "FI-JOB-EXECUTION-LOG-MAIN",
                "leaf": null,
                "method": "GET",
                "name": "工作执行日志",
                "order": 9999,
                "url": "/fi/job_execution_log/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1046,
                "code": "FiMaturityPayment-MAIN",
                "leaf": null,
                "method": "GET",
                "name": "兑付表单",
                "order": 9999,
                "url": "/fi/maturity_payment/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1047,
                "code": "FI-JOB-STATUS-TRACE-LOG-MIAN",
                "leaf": null,
                "method": "GET",
                "name": "工作状态跟踪日志",
                "order": 9999,
                "url": "/fi/job_status_trace_log/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1048,
                "code": "FiMatPayUpload-MAIN",
                "leaf": null,
                "method": "GET",
                "name": "到期兑付上传",
                "order": 9999,
                "url": "/fi/mat_pay_upload/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1049,
                "code": "AAS-RECOMM-UPLOAD-MAIN",
                "leaf": null,
                "method": "GET",
                "name": "资产推荐上传",
                "order": 9999,
                "url": "/fi/aas_recom_upload/main.htm",
                "icon": null,
                "subMenus": []
            }
        ]
    },
    {
        "id": 855,
        "code": "FTC",
        "leaf": null,
        "method": "GET",
        "name": "基金交易业务管理",
        "order": 5,
        "url": "#",
        "icon": null,
        "subMenus": [
            {
                "id": 973,
                "code": "FTC-PORTFOLIO-ORDER-MAIN",
                "leaf": null,
                "method": "GET",
                "name": "组合交易业务",
                "order": 3,
                "url": "/ftc/portfolio_order/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 974,
                "code": "FTC-ASM-PORT-MAIN",
                "leaf": null,
                "method": "GET",
                "name": "组合资产明细",
                "order": 1,
                "url": "/ftc/portfolio_detail/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 975,
                "code": "FTC-ASM-PORT-SNAP-MAIN",
                "leaf": null,
                "method": "GET",
                "name": "组合资产明细快照",
                "order": 2,
                "url": "/ftc/portfolio_snapshot/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 976,
                "code": "FTC-FUND-DETAIL-ALTER",
                "leaf": null,
                "method": "GET",
                "name": "基金详情变更",
                "order": 6,
                "url": "/ftc/fund_detail_alter/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 977,
                "code": "FTC-FUND-DETAIL-SNAPSHOT",
                "leaf": null,
                "method": "GET",
                "name": "基金详情快照",
                "order": 7,
                "url": "/ftc/fund_detail_snapshot/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 978,
                "code": "FTC-FUND-CLEAR-STATUS",
                "leaf": null,
                "method": "GET",
                "name": "基金清盘状态",
                "order": 15,
                "url": "/ftc/fund_clear_status/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 979,
                "code": "FTC-FUND-PROFIT-ALTER",
                "leaf": null,
                "method": "GET",
                "name": "基金利润变更",
                "order": 16,
                "url": "/ftc/fund_profit_alter/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 980,
                "code": "FTC-BATCH-APPLY-FAIL",
                "leaf": null,
                "method": "GET",
                "name": "跑批应用失败",
                "order": 17,
                "url": "/ftc/batch_apply_fail/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 981,
                "code": "FTC-BATCH-CONFIRM-FAIL",
                "leaf": null,
                "method": "GET",
                "name": "跑批确认失败",
                "order": 18,
                "url": "/ftc/batch_confirm_fail/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 982,
                "code": "FTC-FUND-PER-PUR-DAY",
                "leaf": null,
                "method": "GET",
                "name": "个人每日购买基金",
                "order": 23,
                "url": "/ftc/fund_per_purday/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 983,
                "code": "FTC-FUND-TRANS-ORDER-DAY",
                "leaf": null,
                "method": "GET",
                "name": "基金交易业务每日总结",
                "order": 28,
                "url": "/ftc/fund_trans_order_day/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 984,
                "code": "FTC-FUND-TRANS-ORDER-STA",
                "leaf": null,
                "method": "GET",
                "name": "基金交易业务状态",
                "order": 30,
                "url": "/ftc/fund_trans_order_status/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 985,
                "code": "FTC-FUND-TRANS-ORDER-STA-INFO",
                "leaf": null,
                "method": "GET",
                "name": "基金交易业务状态变更",
                "order": 31,
                "url": "/ftc/fund_trans_order_stausInfo/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 986,
                "code": "FTC-PORTFOLIO-TRAN",
                "leaf": null,
                "method": "GET",
                "name": "组合交易与基金交易参照",
                "order": 32,
                "url": "/ftc/portfolio_trans/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 987,
                "code": "FTC-PROD-FROZEN",
                "leaf": null,
                "method": "GET",
                "name": "产品冻结",
                "order": 33,
                "url": "/ftc/prod_frozen/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 988,
                "code": "FTC-PROD-INVENT",
                "leaf": null,
                "method": "GET",
                "name": "产品份额",
                "order": 34,
                "url": "/ftc/prod_invent/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 989,
                "code": "FTC-PROD-INVENT-CHG",
                "leaf": null,
                "method": "GET",
                "name": "产品份额变更",
                "order": 35,
                "url": "/ftc/prod_invent_chg/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 990,
                "code": "FTC-SYS-CON",
                "leaf": null,
                "method": "GET",
                "name": "配置信息",
                "order": 36,
                "url": "/ftc/ftc_sys_con/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 991,
                "code": "FTC-FUND-TOTAL",
                "leaf": null,
                "method": "GET",
                "name": "基金资产汇总",
                "order": 8,
                "url": "/ftc/fund_total/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 992,
                "code": "FTC-MEM-FUND-ACC",
                "leaf": null,
                "method": "GET",
                "name": "用户交易账户",
                "order": 12,
                "url": "/ftc/mem_fund_acc/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 993,
                "code": "FTC-FUND-CLEAR",
                "leaf": null,
                "method": "GET",
                "name": "基金清盘",
                "order": 14,
                "url": "/ftc/fund_clear/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 994,
                "code": "FTC-FUND-TRANS-ORDER-EXCEPT",
                "leaf": null,
                "method": "GET",
                "name": "基金交易业务异常",
                "order": 29,
                "url": "/ftc/fund_trans_order_except/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 995,
                "code": "FTC-FUND-ACCT-ORDER-STATUS",
                "leaf": null,
                "method": "GET",
                "name": "基金账户业务状态",
                "order": 14,
                "url": "/ftc/fund_acct_order_status/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 996,
                "code": "FTC-FUND-BONUS-DETAIL",
                "leaf": null,
                "method": "GET",
                "name": "基金奖金变更管理",
                "order": 4,
                "url": "/ftc/fund_bonus/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 997,
                "code": "FTC-FUND-DETAIL",
                "leaf": null,
                "method": "GET",
                "name": "基金详情管理",
                "order": 5,
                "url": "/ftc/fund_detail/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 998,
                "code": "FTC-FUND-TOTAL-SNAPSHOT",
                "leaf": null,
                "method": "GET",
                "name": "基金资产汇总快照",
                "order": 9,
                "url": "/ftc/fund_total_snapshot/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 999,
                "code": "FTC-MEM-ASSET",
                "leaf": null,
                "method": "GET",
                "name": "用户资产",
                "order": 10,
                "url": "/ftc/mem_asset/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1000,
                "code": "FTC-MEM-ASSET-SNAPSHOT",
                "leaf": null,
                "method": "GET",
                "name": "用户资产快照",
                "order": 11,
                "url": "/ftc/mem_asset_snapshot/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1001,
                "code": "FTC-BATCH-TASK-LOG",
                "leaf": null,
                "method": "GET",
                "name": "跑批任务日志",
                "order": 19,
                "url": "/ftc/batch_task_log/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1002,
                "code": "FTC-FUND-BUY-MEM",
                "leaf": null,
                "method": "GET",
                "name": "购买会员",
                "order": 20,
                "url": "/ftc/fund_buy_mem/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1003,
                "code": "FTC-FUND-DIVID",
                "leaf": null,
                "method": "GET",
                "name": "基金分红",
                "order": 21,
                "url": "/ftc/fund_divid/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1004,
                "code": "FTC-FUND-ACCT-ORDER",
                "leaf": null,
                "method": "GET",
                "name": "基金账户业务",
                "order": 13,
                "url": "/ftc/fund_acct_order/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1005,
                "code": "FTC-FUND-PER-PUR",
                "leaf": null,
                "method": "GET",
                "name": "个人购买基金",
                "order": 24,
                "url": "/ftc/fund_per_pur/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1006,
                "code": "FTC-FUND-PER-REDDAY",
                "leaf": null,
                "method": "GET",
                "name": "个人每日赎回基金",
                "order": 25,
                "url": "/ftc/fund_per_redday/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1007,
                "code": "FTC-PURDAY",
                "leaf": null,
                "method": "GET",
                "name": "每日购买基金",
                "order": 26,
                "url": "/ftc/fund_purday/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1008,
                "code": "FTC-FUND-TRANS-ORDER",
                "leaf": null,
                "method": "GET",
                "name": "基金交易业务",
                "order": 27,
                "url": "/ftc/fund_trans_order/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1009,
                "code": "FTC-FUND-DIVID-STATUS",
                "leaf": null,
                "method": "GET",
                "name": "基金分红状态",
                "order": 22,
                "url": "/ftc/fund_divid_status/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1010,
                "code": "Ftc-HolidayDate-Main",
                "leaf": null,
                "method": "GET",
                "name": "假节日配置",
                "order": 9999,
                "url": "/ftc/holiday_date/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1011,
                "code": "Ftc-TaFundCheckingAcctOrder-MAIN",
                "leaf": null,
                "method": "GET",
                "name": "TA基金账户对账单",
                "order": 9999,
                "url": "/ftc/ta_fund_check_acct_order/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1012,
                "code": "Ftc-TaFundCreateAcctCfmOrder-MAIN",
                "leaf": null,
                "method": "GET",
                "name": "TA基金开户确认单",
                "order": 9999,
                "url": "/ftc/ta_fund_createacct_cfmorder/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1013,
                "code": "Ftc-TaFundPurchasingCfmOrder-MAIN",
                "leaf": null,
                "method": "GET",
                "name": "TA基金申购确认单",
                "order": 9999,
                "url": "/ftc/ta_fund_purchasing_cfmorder/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1014,
                "code": "Ftc-TaFundPurchasingOrder-MAIN",
                "leaf": null,
                "method": "GET",
                "name": "TA基金申购单",
                "order": 9999,
                "url": "/ftc/ta_fund_purchasing_order/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1015,
                "code": "Ftc-TaFundRedeemingCfmOrder-MAIN",
                "leaf": null,
                "method": "GET",
                "name": "TA基金赎回确认单",
                "order": 9999,
                "url": "/ftc/ta_fund_redeeming_cfmOrder/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1016,
                "code": "AsmPortfolioValUpload-MAIN",
                "leaf": null,
                "method": "GET",
                "name": "组合资产上传明细",
                "order": 9999,
                "url": "/ftc/portfolio_valupload/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1017,
                "code": "Ftc-TaFundClearingOrder-Main",
                "leaf": null,
                "method": "GET",
                "name": "基金清盘记录单",
                "order": 9999,
                "url": "/ftc/ta_fund_clearing_order/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1018,
                "code": "Ftc-TaFundCreateAcctOrder-MAIN",
                "leaf": null,
                "method": "GET",
                "name": "TA基金开户单",
                "order": 9999,
                "url": "/ftc/ta_fund_createacct_order/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1019,
                "code": "Ftc-TaFundRedeemingOrder-main",
                "leaf": null,
                "method": "GET",
                "name": "TA基金赎回申请单",
                "order": 9999,
                "url": "/ftc/ta_fund_redeeming_order/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1020,
                "code": "Ftc-TaFundSubscribingCfmOrder-MAIN",
                "leaf": null,
                "method": "GET",
                "name": "TA基金认购确认单",
                "order": 9999,
                "url": "/ftc/ta_fund_subscribing_cfmorder/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1021,
                "code": "Ftc-TaFundSubscribingOrder-main",
                "leaf": null,
                "method": "GET",
                "name": "TA基金认购单",
                "order": 9999,
                "url": "/ftc/ta_fund_subscribing_order/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1022,
                "code": "Ftc-TaFundSubscribingResultOrder-MAIN",
                "leaf": null,
                "method": "GET",
                "name": "TA基金认购结果单",
                "order": 9999,
                "url": "/ftc/ta_fund_subscribing_resultorder/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1023,
                "code": "Ftc-TaFundDividendOrder-MAIN",
                "leaf": null,
                "method": "GET",
                "name": "TA基金分红记录",
                "order": 9999,
                "url": "/ftc/ta_fund_dividend_order/main.htm",
                "icon": null,
                "subMenus": []
            }
        ]
    },
    {
        "id": 856,
        "code": "TRADE",
        "leaf": null,
        "method": "GET",
        "name": "贸易信息",
        "order": 9,
        "url": "#",
        "icon": null,
        "subMenus": [
            {
                "id": 873,
                "code": "TRADE-POSITION",
                "leaf": null,
                "method": "GET",
                "name": "贸易位置",
                "order": 4,
                "url": "/trade/position/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 874,
                "code": "TRADE-MARKET",
                "leaf": null,
                "method": "GET",
                "name": "市场信息",
                "order": 1,
                "url": "/trade/market/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 875,
                "code": "TRADE-PORT-POSITION",
                "leaf": null,
                "method": "GET",
                "name": "组合位置",
                "order": 2,
                "url": "/trade/port_position/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 876,
                "code": "TRADE-PORT-TRADE",
                "leaf": null,
                "method": "GET",
                "name": "贸易组合请求",
                "order": 3,
                "url": "/trade/port_trade/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 877,
                "code": "TRADE-DETAIL",
                "leaf": null,
                "method": "GET",
                "name": "贸易详情",
                "order": 5,
                "url": "/trade/detail/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 878,
                "code": "TRADE-BotBalance-MAIN",
                "leaf": null,
                "method": "GET",
                "name": "账户余额",
                "order": 9999,
                "url": "/trade/balance/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 879,
                "code": "TRADE-TradeReq-MAIN",
                "leaf": null,
                "method": "GET",
                "name": "交易请求",
                "order": 9999,
                "url": "/trade/trade_req/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 880,
                "code": "TRADE-CashDetail-MAIN",
                "leaf": null,
                "method": "GET",
                "name": "兑付明细",
                "order": 9999,
                "url": "/trade/cash_detail/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 881,
                "code": "TRADE-BalanceSnapshot-MAIN",
                "leaf": null,
                "method": "GET",
                "name": "账户余额快照",
                "order": 9999,
                "url": "/trade/balance_snapshot/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 882,
                "code": "TRADE-RedemptionTradeExt-MAIN",
                "leaf": null,
                "method": "GET",
                "name": "延期赎回",
                "order": 9999,
                "url": "/trade/redemption_trade_ext/main.htm",
                "icon": null,
                "subMenus": []
            }
        ]
    },
    {
        "id": 857,
        "code": "TRAN",
        "leaf": null,
        "method": "GET",
        "name": "交易管理",
        "order": 11,
        "url": "#",
        "icon": null,
        "subMenus": [
            {
                "id": 945,
                "code": "TRAN-BUSI-RECORD",
                "leaf": null,
                "method": "GET",
                "name": "业务交易检查记录",
                "order": 1,
                "url": "/trans/busi_record/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 946,
                "code": "TRAN-FUND-RECORD",
                "leaf": null,
                "method": "GET",
                "name": "基金贸易检查记录",
                "order": 3,
                "url": "/trans/fund_record/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 947,
                "code": "TRAN-FUND-TRANS",
                "leaf": null,
                "method": "GET",
                "name": "基金交易",
                "order": 4,
                "url": "/trans/fund_trans/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 948,
                "code": "TRAN-EXCEPT",
                "leaf": null,
                "method": "GET",
                "name": "交易异常",
                "order": 11,
                "url": "/trans/except/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 949,
                "code": "TRAN-PAY-OPT",
                "leaf": null,
                "method": "GET",
                "name": "交易支付选项",
                "order": 12,
                "url": "/trans/pay_opt/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 950,
                "code": "TRAN-ACC-RESULT",
                "leaf": null,
                "method": "GET",
                "name": "交易账务检查结果",
                "order": 5,
                "url": "/trans/acc_result/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 951,
                "code": "TRAN-PAY-RESULT",
                "leaf": null,
                "method": "GET",
                "name": "交易支付核心检查结果",
                "order": 6,
                "url": "/trans/pay_result/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 952,
                "code": "TRAN-PAY",
                "leaf": null,
                "method": "GET",
                "name": "付款支付",
                "order": 7,
                "url": "/trans/pay/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 953,
                "code": "TRAN-PAYMENT",
                "leaf": null,
                "method": "GET",
                "name": "交易支付",
                "order": 8,
                "url": "/trans/payment/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 954,
                "code": "TRAN-PAYMENT-EVENT",
                "leaf": null,
                "method": "GET",
                "name": "交易支付事件",
                "order": 9,
                "url": "/trans/payment_event/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 955,
                "code": "TRAN-EVENT",
                "leaf": null,
                "method": "GET",
                "name": "交易事件",
                "order": 10,
                "url": "/trans/event/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 956,
                "code": "TRAN-PROD",
                "leaf": null,
                "method": "GET",
                "name": "交易产品",
                "order": 13,
                "url": "/trans/prod/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 957,
                "code": "TRAN-TRAN",
                "leaf": null,
                "method": "GET",
                "name": "交易",
                "order": 14,
                "url": "/trans/tran/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 958,
                "code": "TRAN-BUSI-RESULT",
                "leaf": null,
                "method": "GET",
                "name": "业务交易检查结果",
                "order": 2,
                "url": "/trans/busi_result/main.htm",
                "icon": null,
                "subMenus": []
            }
        ]
    },
    {
        "id": 858,
        "code": "MARKET",
        "leaf": null,
        "method": "GET",
        "name": "营销管理",
        "order": 7,
        "url": "#",
        "icon": null,
        "subMenus": [
            {
                "id": 862,
                "code": "MAR-SUP-PROD",
                "leaf": null,
                "method": "GET",
                "name": "福利券支持产品",
                "order": 5,
                "url": "/market/sup_prod/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 863,
                "code": "MAR-USE-REC",
                "leaf": null,
                "method": "GET",
                "name": "福利券使用记录",
                "order": 6,
                "url": "/market/use_rec/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 864,
                "code": "MAR-ACT-COU",
                "leaf": null,
                "method": "GET",
                "name": "福利券信息",
                "order": 1,
                "url": "/market/act_cou/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 865,
                "code": "MAR-EVENT",
                "leaf": null,
                "method": "GET",
                "name": "福利券事件",
                "order": 3,
                "url": "/market/event/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 866,
                "code": "MAR-RULE",
                "leaf": null,
                "method": "GET",
                "name": "福利券规则",
                "order": 4,
                "url": "/market/rule/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 867,
                "code": "MAR-COU-USER",
                "leaf": null,
                "method": "GET",
                "name": "福利券使用者",
                "order": 2,
                "url": "/market/cou_user/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 868,
                "code": "Market-JobStatusTraceLog-MAIN",
                "leaf": null,
                "method": "GET",
                "name": "工作状态跟踪日志",
                "order": 9999,
                "url": "/market/job_status_traceLog/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 869,
                "code": "Market-ActivityUser-MAIN",
                "leaf": null,
                "method": "GET",
                "name": "营销活动用户",
                "order": 9999,
                "url": "/market/activity_user/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 870,
                "code": "Market-JobExecutionLog-MAIN",
                "leaf": null,
                "method": "GET",
                "name": "工作执行日志",
                "order": 9999,
                "url": "/market/job_execution_log/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 871,
                "code": "Market-ActivityInfo-main",
                "leaf": null,
                "method": "GET",
                "name": "营销活动信息",
                "order": 9999,
                "url": "/market/activity_info/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 872,
                "code": "Market-UserOper-main",
                "leaf": null,
                "method": "GET",
                "name": "营销用户活动操作",
                "order": 9999,
                "url": "/market/user_oper/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1554,
                "code": "SHARE-INFO",
                "leaf": null,
                "method": "POST",
                "name": "分享信息管理",
                "order": 65,
                "url": "/share/shareInfo/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1559,
                "code": "BATCH-ISSUE-COUPON",
                "leaf": null,
                "method": "POST",
                "name": "批量发券管理",
                "order": 60,
                "url": "/market/issue_coupon/main.htm",
                "icon": null,
                "subMenus": []
            }
        ]
    },
    {
        "id": 859,
        "code": "PAY",
        "leaf": null,
        "method": "GET",
        "name": "支付管理",
        "order": 8,
        "url": "#",
        "icon": null,
        "subMenus": [
            {
                "id": 900,
                "code": "PAY-PAY",
                "leaf": null,
                "method": "GET",
                "name": "支付单",
                "order": 9,
                "url": "/payment/pay/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 901,
                "code": "PAY-PAY-EVENT",
                "leaf": null,
                "method": "GET",
                "name": "支付单事件",
                "order": 10,
                "url": "/payment/pay_event/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 902,
                "code": "PAY-DCP-BANK",
                "leaf": null,
                "method": "GET",
                "name": "支付商与银行映射",
                "order": 3,
                "url": "/payment/dcp_card/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 903,
                "code": "PAY-DCP-BIND",
                "leaf": null,
                "method": "GET",
                "name": "DCP_BINDING",
                "order": 4,
                "url": "/payment/dcp_bind/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 904,
                "code": "PAY-DCP",
                "leaf": null,
                "method": "GET",
                "name": "DCP_PI",
                "order": 5,
                "url": "/payment/dcp/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 905,
                "code": "PAY-DCP-WITHDRAW",
                "leaf": null,
                "method": "GET",
                "name": "支付商撤销映射",
                "order": 7,
                "url": "/payment/withdraw/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 906,
                "code": "PAY-DCP-RECHARGE",
                "leaf": null,
                "method": "GET",
                "name": "支付商充值映射",
                "order": 6,
                "url": "/payment/recharge/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 907,
                "code": "PAY-BANK",
                "leaf": null,
                "method": "GET",
                "name": "付款银行",
                "order": 1,
                "url": "/payment/bank/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 908,
                "code": "PAY-CARD",
                "leaf": null,
                "method": "GET",
                "name": "付款银行卡",
                "order": 2,
                "url": "/payment/card/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 909,
                "code": "PAY-PAY-INSTR",
                "leaf": null,
                "method": "GET",
                "name": "支付方式",
                "order": 11,
                "url": "/payment/instr/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 910,
                "code": "PAY-PAY-INSTR-TYPE",
                "leaf": null,
                "method": "GET",
                "name": "支付方式类型",
                "order": 12,
                "url": "/payment/instr_type/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 911,
                "code": "PAY-PROV",
                "leaf": null,
                "method": "GET",
                "name": "支付商",
                "order": 13,
                "url": "/payment/provider/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 912,
                "code": "PAY-REG-PAY-INST",
                "leaf": null,
                "method": "GET",
                "name": "支付凭证注册",
                "order": 17,
                "url": "/payment/regist_pay/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 913,
                "code": "PAY-DCP-XREF",
                "leaf": null,
                "method": "GET",
                "name": "支付商外部参照",
                "order": 8,
                "url": "/payment/dcp_provinfo/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 914,
                "code": "PAY-PROV-MER-INFO",
                "leaf": null,
                "method": "GET",
                "name": "支付商信息",
                "order": 14,
                "url": "/payment/merchant_info/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 915,
                "code": "PAY-PROV-MER-MAP",
                "leaf": null,
                "method": "GET",
                "name": "支付商映射",
                "order": 15,
                "url": "/payment/merchant_map/main.htm",
                "icon": null,
                "subMenus": []
            }
        ]
    },
    {
        "id": 860,
        "code": "BUSINESS",
        "leaf": null,
        "method": "GET",
        "name": "订单管理",
        "order": 10,
        "url": "#",
        "icon": null,
        "subMenus": [
            {
                "id": 897,
                "code": "BUSS-ORDER",
                "leaf": null,
                "method": "GET",
                "name": "订单业务",
                "order": 1,
                "url": "/oms/order/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 898,
                "code": "BUSS-ORDER-EVENT",
                "leaf": null,
                "method": "GET",
                "name": "订单业务事件",
                "order": 2,
                "url": "/oms/event/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 899,
                "code": "BUSS-OPTION-SNAP",
                "leaf": null,
                "method": "GET",
                "name": "订单快照",
                "order": 3,
                "url": "/oms/snap/main.htm",
                "icon": null,
                "subMenus": []
            }
        ]
    },
    {
        "id": 861,
        "code": "ASM",
        "leaf": null,
        "method": "GET",
        "name": "资产管理",
        "order": 6,
        "url": "#",
        "icon": null,
        "subMenus": [
            {
                "id": 916,
                "code": "ASM-JOBEXECUTION-LOG-MAIN",
                "leaf": null,
                "method": "GET",
                "name": "工作执行日志",
                "order": 9999,
                "url": "/asm/job_execution_log/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 917,
                "code": "ASM-JOBEXECUTIONLOG-MAIN",
                "leaf": null,
                "method": "GET",
                "name": "工作状态跟踪日志",
                "order": 9999,
                "url": "/asm/job_status_trace_log/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 918,
                "code": "AM-ASSET-NPVP-HIS",
                "leaf": null,
                "method": "GET",
                "name": "资产历史价格",
                "order": 5,
                "url": "/asm/asset_npvp_his/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 919,
                "code": "AM-EVENT",
                "leaf": null,
                "method": "GET",
                "name": "事件",
                "order": 16,
                "url": "/asm/event/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 920,
                "code": "AM-FEE-INFO",
                "leaf": null,
                "method": "GET",
                "name": "费用信息",
                "order": 17,
                "url": "/asm/fee_info/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 921,
                "code": "AM-PROD-FUND-PLAN",
                "leaf": null,
                "method": "GET",
                "name": "产品资金募集计划",
                "order": 19,
                "url": "/asm/prod_fund_plan/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 922,
                "code": "AM-PROD-INFO",
                "leaf": null,
                "method": "GET",
                "name": "产品信息",
                "order": 20,
                "url": "/asm/prod_info/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 923,
                "code": "AM-PROD-INTERET-INFO",
                "leaf": null,
                "method": "GET",
                "name": "产品利率信息",
                "order": 21,
                "url": "/asm/prod_interest_info/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 924,
                "code": "AM-PROD-NPVP",
                "leaf": null,
                "method": "GET",
                "name": "产品价格",
                "order": 22,
                "url": "/asm/prod_npvp/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 925,
                "code": "AM-PROD-NPVP-HIS",
                "leaf": null,
                "method": "GET",
                "name": "产品历史价格",
                "order": 23,
                "url": "/asm/prod_npvp_his/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 926,
                "code": "AM-PROD-TOBE-ISSUE",
                "leaf": null,
                "method": "GET",
                "name": "产品发行",
                "order": 25,
                "url": "/asm/prod_issue/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 927,
                "code": "AM-PROD-FEE-DEL",
                "leaf": null,
                "method": "GET",
                "name": "产品费用明细",
                "order": 18,
                "url": "/asm/prod_fee_del/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 928,
                "code": "AM-PROD-SPLIT-CONF",
                "leaf": null,
                "method": "GET",
                "name": "产品分拆配置",
                "order": 24,
                "url": "/asm/prod_split_conf/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 929,
                "code": "AM-ASSET-FEE",
                "leaf": null,
                "method": "GET",
                "name": "资产费用明细",
                "order": 1,
                "url": "/asm/asset_fee/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 930,
                "code": "AM-ASSET-INFO",
                "leaf": null,
                "method": "GET",
                "name": "资产信息",
                "order": 2,
                "url": "/asm/asset_info/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 931,
                "code": "AM-ASSET-INTEREST",
                "leaf": null,
                "method": "GET",
                "name": "资产利率",
                "order": 3,
                "url": "/asm/asset_interest/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 932,
                "code": "AM-ASSET-POOL",
                "leaf": null,
                "method": "GET",
                "name": "资产池",
                "order": 11,
                "url": "/asm/asset_pool/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 933,
                "code": "AM-ASSET-RISK",
                "leaf": null,
                "method": "GET",
                "name": "资产风险",
                "order": 14,
                "url": "/asm/asset_risk/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 934,
                "code": "AM-ATTR",
                "leaf": null,
                "method": "GET",
                "name": "属性",
                "order": 15,
                "url": "/asm/attr/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 935,
                "code": "AM-ASSET-NPVP",
                "leaf": null,
                "method": "GET",
                "name": "资产价格",
                "order": 4,
                "url": "/asm/asset_npvp/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 936,
                "code": "AM-ASSET-PACK",
                "leaf": null,
                "method": "GET",
                "name": "资产包",
                "order": 6,
                "url": "/asm/asset_pack/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 937,
                "code": "AM-ASSET-PACK-ATTR",
                "leaf": null,
                "method": "GET",
                "name": "资产包属性",
                "order": 7,
                "url": "/asm/asset_pack_attr/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 938,
                "code": "AM-ASSET-PACK-DEL",
                "leaf": null,
                "method": "GET",
                "name": "资产包明细",
                "order": 8,
                "url": "/asm/asset_pack_del/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 939,
                "code": "AM-ASSETPACK-PROD",
                "leaf": null,
                "method": "GET",
                "name": "资产包产品",
                "order": 9,
                "url": "/asm/asset_pack_prod/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 940,
                "code": "AM-ASSET-PART",
                "leaf": null,
                "method": "GET",
                "name": "资产参与者",
                "order": 10,
                "url": "/asm/asset_part/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 941,
                "code": "AM-ASSET-POOL-ATTR",
                "leaf": null,
                "method": "GET",
                "name": "资产池属性",
                "order": 12,
                "url": "/asm/asset_pool_attr/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 942,
                "code": "ASSET-POOL-DEL",
                "leaf": null,
                "method": "GET",
                "name": "资产池明细",
                "order": 13,
                "url": "/asm/asset_pool_del/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 943,
                "code": "ASSET-PACKAGE-NPVPS-MAIN",
                "leaf": null,
                "method": "GET",
                "name": "每股净资产查询",
                "order": 9999,
                "url": "/asm/asset_pack_npvps/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 944,
                "code": "ASSET-PACKAGE-NPVPS-HISTORY-MAIN",
                "leaf": null,
                "method": "GET",
                "name": "每股净资产历史",
                "order": 9999,
                "url": "/asm/asset_pack_npvps_history/main.htm",
                "icon": null,
                "subMenus": []
            }
        ]
    },
    {
        "id": 1534,
        "code": "NOTIFY",
        "leaf": null,
        "method": "GET",
        "name": "通知管理",
        "order": 13,
        "url": "#",
        "icon": null,
        "subMenus": [
            {
                "id": 1535,
                "code": "NOTIFY-ANNOUNCE",
                "leaf": null,
                "method": "GET",
                "name": "公告管理",
                "order": 1,
                "url": "/notify/announce/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1536,
                "code": "NOTIFY-INBOX-TEMPALTE",
                "leaf": null,
                "method": "GET",
                "name": "站内信模板",
                "order": 2,
                "url": "/notify/inboxmsgtemplate/main.htm",
                "icon": null,
                "subMenus": []
            },
            {
                "id": 1537,
                "code": "NOTIFY-SMS-TEMPLATE",
                "leaf": null,
                "method": "GET",
                "name": "邮箱与短信模板",
                "order": 3,
                "url": "/notify/smstemplate/main.htm",
                "icon": null,
                "subMenus": []
            }
        ]
    }
];